# Generated by Django 5.2.5 on 2025-08-27 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel')),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, null=True)),
                ('rf_subject', models.CharField(max_length=255, null=True)),
                ('svetofor', models.IntegerField(null=True)),
                ('svet_index', models.IntegerField(null=True)),
                ('plan', models.IntegerField(null=True)),
                ('fact', models.IntegerField(null=True)),
                ('lack', models.IntegerField(null=True)),
                ('lack_per', models.CharField(max_length=10, null=True)),
                ('lack_text', models.CharField(max_length=255, null=True)),
                ('text_to_dash', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
