# Generated by Django 5.2.5 on 2025-08-28 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects_RF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tech',
            name='rf_subject',
        ),
        migrations.AlterField(
            model_name='tech',
            name='lack_per',
            field=models.FloatField(null=True),
        ),
        migrations.CreateModel(
            name='ContPlaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svetofor', models.IntegerField(null=True)),
                ('population', models.IntegerField(null=True)),
                ('fact_mno', models.IntegerField(null=True)),
                ('fact_fgis_kp', models.IntegerField(null=True)),
                ('fact_mno_ts', models.IntegerField(null=True)),
                ('lack_kp', models.IntegerField(null=True)),
                ('container_places_per_1k', models.FloatField(null=True)),
                ('container_places_plan', models.IntegerField(null=True)),
                ('lack_in_per', models.FloatField(null=True)),
                ('container_places_fgis_fill', models.FloatField(null=True)),
                ('rf_subject_cont_places', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf')),
            ],
        ),
        migrations.CreateModel(
            name='Containers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('svetofor', models.IntegerField(null=True)),
                ('population', models.IntegerField(null=True)),
                ('cont_fact_fgis', models.IntegerField(null=True)),
                ('cont_fact_ts', models.IntegerField(null=True)),
                ('lack_containers', models.IntegerField(null=True)),
                ('containers_per_1k', models.FloatField(null=True)),
                ('containers_plan', models.IntegerField(null=True)),
                ('containers_lack_in_per', models.FloatField(null=True)),
                ('containers_fgis_fill', models.FloatField(null=True)),
                ('rf_subject_containers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf')),
            ],
        ),
        migrations.AddField(
            model_name='tech',
            name='rf_subject_tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf'),
        ),
        migrations.CreateModel(
            name='Svod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbr', models.CharField(max_length=10, null=True)),
                ('risks_zones', models.CharField(max_length=255, null=True)),
                ('mobile_app', models.CharField(max_length=255, null=True)),
                ('road_map_ro', models.BooleanField(default=False)),
                ('container_places_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.contplaces')),
                ('containers_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.containers')),
                ('rf_subject_svod', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf')),
                ('tech_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='regions.tech')),
            ],
        ),
    ]
