# Generated by Django 5.2.5 on 2025-09-02 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0002_subjects_rf_remove_tech_rf_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='rf_subject_tech',
            field=models.ForeignKey(db_column='region', null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf'),
        ),
    ]
