# Generated by Django 5.2.5 on 2025-09-02 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0003_alter_tech_rf_subject_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='rf_subject_tech',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf'),
        ),
    ]
