# Generated by Django 5.2.5 on 2025-09-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0004_alter_tech_rf_subject_tech'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svod',
            name='road_map_ro',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
