# Generated by Django 5.2.6 on 2025-09-19 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0005_alter_svod_road_map_ro'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeightControlFGIS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_fgis_fill', models.FloatField(db_comment='формат 0.0', null=True)),
                ('rf_subject_weight', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf')),
            ],
        ),
    ]
