# Generated by Django 5.2.6 on 2025-09-22 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0006_weightcontrolfgis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerPlacesPhotofixation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_fixation_fill', models.FloatField(db_comment='формат 0.0, уже проценты', null=True)),
                ('rf_subject_photo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf')),
            ],
        ),
    ]
