# Generated by Django 5.2.6 on 2025-09-23 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0007_containerplacesphotofixation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlonassData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tech_data', models.IntegerField(null=True)),
                ('transducer', models.IntegerField(null=True)),
                ('glonass_data_fill', models.FloatField(db_comment='формат 0.0', null=True)),
                ('rf_subject_glonass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf')),
            ],
        ),
        migrations.CreateModel(
            name='VideoFixation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cameras_exist', models.BooleanField(default=False)),
                ('integration_in_process', models.BooleanField(default=False)),
                ('actually_transmitting', models.BooleanField(default=False)),
                ('rf_subject_videofixation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf')),
            ],
        ),
    ]
