# Generated by Django 5.2.6 on 2025-09-23 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0008_glonassdata_videofixation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainersPlacesPurchases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.FloatField(db_comment='млн руб', null=True)),
                ('cont_places_additional', models.CharField(max_length=255, null=True)),
                ('cont_places_additional_per', models.FloatField(db_comment='проценты формат 0.0', null=True)),
                ('containers_additional', models.CharField(max_length=255, null=True)),
                ('containers_additional_per', models.FloatField(db_comment='проценты формат 0.0', null=True)),
                ('rf_subject_contplaces_purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf')),
            ],
        ),
    ]
