# Generated by Django 5.2.6 on 2025-09-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0009_containersplacespurchases'),
    ]

    operations = [
        migrations.AddField(
            model_name='weightcontrolfgis',
            name='mesuared',
            field=models.BooleanField(default=False),
        ),
    ]
