# Generated by Django 5.2.6 on 2025-09-23 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0010_weightcontrolfgis_mesuared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weightcontrolfgis',
            old_name='mesuared',
            new_name='not_mesuared',
        ),
    ]
