# Generated by Django 5.2.6 on 2025-09-23 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0011_rename_mesuared_weightcontrolfgis_not_mesuared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerplacesphotofixation',
            name='rf_subject_photo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf', unique=True),
        ),
        migrations.AlterField(
            model_name='containersplacespurchases',
            name='rf_subject_contplaces_purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf', unique=True),
        ),
        migrations.AlterField(
            model_name='glonassdata',
            name='rf_subject_glonass',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf', unique=True),
        ),
        migrations.AlterField(
            model_name='videofixation',
            name='rf_subject_videofixation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf', unique=True),
        ),
        migrations.AlterField(
            model_name='weightcontrolfgis',
            name='rf_subject_weight',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf', unique=True),
        ),
    ]
