# Generated by Django 5.2.6 on 2025-09-23 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0012_alter_containerplacesphotofixation_rf_subject_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerplacesphotofixation',
            name='rf_subject_photo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf'),
        ),
        migrations.AlterField(
            model_name='containersplacespurchases',
            name='rf_subject_contplaces_purchase',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf'),
        ),
        migrations.AlterField(
            model_name='glonassdata',
            name='rf_subject_glonass',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf'),
        ),
        migrations.AlterField(
            model_name='videofixation',
            name='rf_subject_videofixation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf'),
        ),
        migrations.AlterField(
            model_name='weightcontrolfgis',
            name='rf_subject_weight',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf'),
        ),
    ]
