# Generated by Django 5.2.6 on 2025-09-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0013_alter_containerplacesphotofixation_rf_subject_photo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='containersplacespurchases',
            name='cont_places_fact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='containersplacespurchases',
            name='cont_places_plan',
            field=models.IntegerField(null=True),
        ),
    ]
