# Generated by Django 5.2.6 on 2025-09-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0014_delete_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='containersplacespurchases',
            name='containers_fact',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='containersplacespurchases',
            name='containers_plan',
            field=models.IntegerField(null=True),
        ),
    ]
