# Generated by Django 5.2.6 on 2025-09-24 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0015_containersplacespurchases_containers_fact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containersplacespurchases',
            name='cont_places_additional',
        ),
        migrations.RemoveField(
            model_name='containersplacespurchases',
            name='containers_additional',
        ),
    ]
