# Generated by Django 5.2.6 on 2025-09-24 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regions', '0016_remove_containersplacespurchases_cont_places_additional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tech',
            name='rf_subject_tech',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='regions.subjects_rf'),
        ),
    ]
